# -*- coding: utf-8 -*-
"""Deploy all text Visualization dg Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1357QBXlVO-EJiYyVrAl0AzGHyez_lLWs
"""

#!pip install PySastrawi
#!pip install streamlit

"""# Instalasi library yang dibutuhkan"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import nltk
import re
from PIL import Image
import pandas as pd
import string
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
import io

import Sastrawi
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory_stem = StemmerFactory()
stemmer = factory_stem.create_stemmer()
from nltk.stem import WordNetLemmatizer
lemmatizer_english = WordNetLemmatizer()

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
factory_sw = StopWordRemoverFactory()
stopwords_indo = factory_sw.get_stop_words()
from nltk.corpus import stopwords
stopwords_en = list(stopwords.words('english'))

import networkx as nx
from tqdm import tqdm
from networkx.algorithms import community
import logging
#from random import random
#import random

"""# Text Visualization by Kadence Indonesia"""

def preprocessing(kalimat, lang="Indonesia", tambahan_stopwords=[]):
  hasil = []

  #list stop words, bisa ditambahkan sesuai kebutuhan
  kalimat = str(kalimat).translate(str.maketrans("","",string.punctuation))
  kalimat = re.sub(r"\d+", "", kalimat)
  norm = kalimat.lower()
  if lang == "Indonesia":
    stem = stemmer.stem(norm)
    list_token = nltk.word_tokenize(stem)
    stopwords = stopwords_indo
  else:
    lemma = lemmatizer_english.lemmatize(norm)
    list_token = nltk.word_tokenize(lemma)
    stopwords = stopwords_en
  if len(tambahan_stopwords) > 0:
    stopwords.extend(tambahan_stopwords)

  for i in list_token:
      if i not in stopwords:
        hasil.append(i)
  gabung = " ".join(hasil)

  return gabung

text = st.text_area("Masukkan teks di sini:")
bahasa = st.selectbox("Bahasa dominan di teks ini : ", ("English", "Indonesia"),)
background_color = st.color_picker("Warna Latar", "#FFFFFF")
text_color = st.selectbox("Atur warna teks? ", ("Tidak", "Ya"),)
if text_color == "Ya":
  text_color_ = st.color_picker("Text color", "#000000")

tambahan_stopwords = st.text_input("Input stopwords (pisahkan kata dengan koma): ", "nggak", )
prepro_text = preprocessing(text, lang=bahasa, tambahan_stopwords=tambahan_stopwords.split(","))

if st.button("Generate"):
    if text:
        if text_color == "Ya":
            wordcloud = WordCloud(width=800, height=400, background_color=background_color,
                                  color_func=lambda *args, **kwargs: text_color_).generate(prepro_text)
        else:
            wordcloud = WordCloud(width=800, height=400, background_color=background_color).generate(prepro_text)
        fig, ax = plt.subplots()
        ax.imshow(wordcloud, interpolation='bilinear')
        ax.axis("off")
        st.pyplot(fig)

        # Simpan gambar ke dalam format bytes
        img_bytes = io.BytesIO()
        plt.savefig(img_bytes, format="png", bbox_inches='tight')
        img_bytes.seek(0)

        # Tombol download gambar
        st.download_button(
            label="Download WordCloud",
            data=img_bytes,
            file_name="wordcloud.png",
            mime="image/png"
        )

    else:
        st.error("Teks tidak boleh kosong!")

